# Generated by Django 2.0.3 on 2019-06-10 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5)),
                ('name', models.CharField(max_length=64)),
                ('toppings', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed')], default='pending', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('end_sum', models.FloatField(blank=True, default=0, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.FoodType'),
        ),
    ]
